apiVersion: apps/v1
kind: Deployment
metadata:
  name: projportifolio
spec:
  selector:
    matchLabels:
      app: projportifolio
  template:
    metadata:
      labels:
        app: projportifolio
    spec:
      containers:
      - name: projportifolio
        image: viniciuscaol/projportifolio:v{{TAG}}
        ports:
        - containerPort: 80